name: JUnit Results Aggregator
description: Aggregator for JUnit reports
author: Michael Stringer

inputs:
  upload-report:
    description: If true then upload reports in HTML & JSON formats
    required: false
    default: 'true'
  artifact-name:
    description: Name of the artifact to store reports in
    required: false
  retention-days:
    description: Number of days to retain report artifact for
    required: false

runs:
  using: node20
  main: dist/index.js
